# rloop設定ファイル

## ステータス管理用ファイル
status_file = '.rloop.status'

## コーディングエージェントを実行するコマンド
## stdin で指示が入力されます
command = ['opencode', 'run', '-']

verify_command = ["go", "test", "./..."]
notify_command = ["echo", "DONE!"]

## 指示内容
## .status_file にステータス管理ファイル名が入力されます
goal = """
ここにAIへの指示を入力します。

## ルール
- タスク完了時: echo DONE > {{ .status_file }}
- ユーザーに確認を求める場合: echo PAUSE > {{ .status_file }}

{{ with .verify_result }}
## 検証コマンド結果
{{ . }}
{{ end }}
"""
